### PR TITLE
Mess

### PR DESCRIPTION
**Pull request by ediosyncratic**
A heavily rebased version of Julien's patches_recovered_from_old_installation_2 branch.
Removes some transients I wasn't happy with and deals with the mass space-changing all in pure-space commits.

### CODE REVIEW

**Review by julien-picalausa — COMMENTED** [review]
It would make more sense to have "Add support for a configurable private help URL prefix." before "Added URLs to extra help pages.", since this is the one setting baseExtraHelpURL.

**Comment by julien-picalausa** [comment]
Looks good otherwise though. I love the whitespace cleanup.

**Comment by ediosyncratic** [comment]
Pull branch to see true order.
GitHub review lists branch in mangled order.

	Eddy.

**Comment by julien-picalausa** [comment]
Alright. It's fine then. Feel free to merge.

**Pull request merged**
